# Generated by Django 6.1.1 on 2026-09-23 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Unidade / Loja')),
                ('tipo', models.CharField(choices=[('loja', 'Loja Física / Salão de Vendas'), ('armazem', 'Depósito Central / Galpão'), ('filial', 'Filial de Distribuição')], default='loja', max_length=20, verbose_name='Tipo de Instalação')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Gerente / Encarregado')),
            ],
            options={
                'verbose_name': 'Depósito / Loja',
                'verbose_name_plural': 'Depósitos & Lojas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=150, verbose_name='Razão Social / Fornecedor')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('contato_nome', models.CharField(blank=True, max_length=100, verbose_name='Representante')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(max_length=30, unique=True, verbose_name='Código SKU')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Produto')),
                ('categoria', models.CharField(choices=[('eletronicos', 'Eletrônicos & Informática'), ('acessorios', 'Acessórios & Periféricos'), ('audio', 'Áudio & Vídeo'), ('cabos', 'Cabos & Conectividade')], default='acessorios', max_length=30, verbose_name='Categoria')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo (R$)')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda (R$)')),
                ('ponto_de_pedido', models.PositiveIntegerField(default=10, verbose_name='Ponto de Pedido (Estoque Mínimo)')),
                ('fornecedor_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='estoque.fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Compra / Recebimento)'), ('saida_venda', 'Saída (Venda no Balcão da Loja)'), ('ajuste', 'Ajuste de Inventário / Perda')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Movimentada')),
                ('documento_referencia', models.CharField(blank=True, max_length=60, verbose_name='Nº Nota Fiscal / Cupom Fiscal')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Observações')),
                ('data_movimentacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data / Hora')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.deposito', verbose_name='Depósito / Loja')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.fornecedor', verbose_name='Fornecedor de Origem (se entrada)')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='SaldoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Saldo em Estoque')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='estoque.deposito', verbose_name='Depósito / Loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='estoque.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Saldo por Depósito',
                'verbose_name_plural': 'Saldos por Depósito',
                'unique_together': {('deposito', 'produto')},
            },
        ),
    ]
